In [ ]:
import numpy as np
import sympy as sp
np.random.seed(59)
A = np.random.randint(0,10,(5,5))
A
sp.Matrix(A)

Matrix([
[1, 7, 5, 9, 0],
[3, 0, 3, 7, 9],
[0, 9, 4, 5, 2],
[6, 1, 6, 2, 4],
[1, 2, 8, 9, 8]])

In [ ]:
A[1]=A[1]-3*A[0]
A

array([[  1,   7,   5,   9,   0],
       [  0, -21, -12, -20,   9],
       [  0,   9,   4,   5,   2],
       [  6,   1,   6,   2,   4],
       [  1,   2,   8,   9,   8]])

In [ ]:
A[3]=A[3]-6*A[0]
A

array([[  1,   7,   5,   9,   0],
       [  0, -21, -12, -20,   9],
       [  0,   9,   4,   5,   2],
       [  0, -41, -24, -52,   4],
       [  1,   2,   8,   9,   8]])

In [ ]:
A[4]=A[4]-A[0]
A

array([[  1,   7,   5,   9,   0],
       [  0, -21, -12, -20,   9],
       [  0,   9,   4,   5,   2],
       [  0, -41, -24, -52,   4],
       [  0,  -5,   3,   0,   8]])

In [ ]:
A[1]=A[1]/(-21)
A

array([[  1,   7,   5,   9,   0],
       [  0,   1,   0,   0,   0],
       [  0,   9,   4,   5,   2],
       [  0, -41, -24, -52,   4],
       [  0,  -5,   3,   0,   8]])

In [ ]:
A[2]=A[2]-9*A[1]
A

array([[  1,   7,   5,   9,   0],
       [  0,   1,   0,   0,   0],
       [  0,   0,   4,   5,   2],
       [  0, -41, -24, -52,   4],
       [  0,  -5,   3,   0,   8]])

In [ ]:
A[3]=A[3]+41*A[1]
A

array([[  1,   7,   5,   9,   0],
       [  0,   1,   0,   0,   0],
       [  0,   0,   4,   5,   2],
       [  0,   0, -24, -52,   4],
       [  0,  -5,   3,   0,   8]])

In [ ]:
A[4]=A[4]+5*A[1]
A

array([[  1,   7,   5,   9,   0],
       [  0,   1,   0,   0,   0],
       [  0,   0,   4,   5,   2],
       [  0,   0, -24, -52,   4],
       [  0,   0,   3,   0,   8]])

In [ ]:
A[2]=A[2]/4
A

array([[  1,   7,   5,   9,   0],
       [  0,   1,   0,   0,   0],
       [  0,   0,   1,   1,   0],
       [  0,   0, -24, -52,   4],
       [  0,   0,   3,   0,   8]])

In [ ]:
A[3]=A[3]+24*A[2]
A

array([[  1,   7,   5,   9,   0],
       [  0,   1,   0,   0,   0],
       [  0,   0,   1,   1,   0],
       [  0,   0,   0, -28,   4],
       [  0,   0,   3,   0,   8]])

In [ ]:
A[4]=A[4]-3*A[2]
A

array([[  1,   7,   5,   9,   0],
       [  0,   1,   0,   0,   0],
       [  0,   0,   1,   1,   0],
       [  0,   0,   0, -28,   4],
       [  0,   0,   0,  -3,   8]])

In [ ]:
A[3]=A[3]/(-28)
A

array([[ 1,  7,  5,  9,  0],
       [ 0,  1,  0,  0,  0],
       [ 0,  0,  1,  1,  0],
       [ 0,  0,  0,  1,  0],
       [ 0,  0,  0, -3,  8]])

In [ ]:
A[4]=A[4]+3*A[3]
A

array([[1, 7, 5, 9, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 8]])

In [ ]:
A[4]=A[4]/8
A

array([[1, 7, 5, 9, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])